### Numpy Mastery Assignment
- Answer all questions
- Submission : 20th September 2022

In [1]:
#import library
import numpy as np

1. Create a 1D array of numbers from 0 to 9

In [2]:
# create array
arr_1 = np.arange(0,10)
# display array
arr_1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

2. Create a 3x3 numpy of all True 

In [3]:
# create array
arr_2 = np.full((3,3), True)
# display array
arr_2

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

3. Create an array of numbers from 20 to 39

In [4]:
# create array
arr_3 = np.arange(20,40)
# display array
arr_3

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
       37, 38, 39])

4. Replace all odd numbers in Q3 by -1

In [5]:
# change odd numbers in numpy array to -1
arr_3[arr_3 % 2 != 0] = -1
# display array
arr_3

array([20, -1, 22, -1, 24, -1, 26, -1, 28, -1, 30, -1, 32, -1, 34, -1, 36,
       -1, 38, -1])

5. Create two arrays of length 10 and print out  common items in both arrays

In [6]:
# create two arrays
arr_4 = np.arange(100,110)
arr_5 = np.arange(105,115)
# display common elements in the two arrays
print(np.intersect1d(arr_4,arr_5))

[105 106 107 108 109]


6.  Create a 5x5 identity matrix

In [7]:
# create array
mat1 = np.eye(5)
# display array
mat1

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

7. In the code cell below define and print a set of arrays defined x, y and z. The array x should be take the form [10 12 9 2 20], y should have  101  values from  10  to  20  inclusive and z should be a  2×3  array of ones.

In [8]:
# create arrays
x = np.array([10,12,2,9,20])
y = np.linspace(10,20,101)
z = np.ones((2,3))

# print arrays
print('x:', x)
print('y:', y)
print('z:',z)

x: [10 12  2  9 20]
y: [10.  10.1 10.2 10.3 10.4 10.5 10.6 10.7 10.8 10.9 11.  11.1 11.2 11.3
 11.4 11.5 11.6 11.7 11.8 11.9 12.  12.1 12.2 12.3 12.4 12.5 12.6 12.7
 12.8 12.9 13.  13.1 13.2 13.3 13.4 13.5 13.6 13.7 13.8 13.9 14.  14.1
 14.2 14.3 14.4 14.5 14.6 14.7 14.8 14.9 15.  15.1 15.2 15.3 15.4 15.5
 15.6 15.7 15.8 15.9 16.  16.1 16.2 16.3 16.4 16.5 16.6 16.7 16.8 16.9
 17.  17.1 17.2 17.3 17.4 17.5 17.6 17.7 17.8 17.9 18.  18.1 18.2 18.3
 18.4 18.5 18.6 18.7 18.8 18.9 19.  19.1 19.2 19.3 19.4 19.5 19.6 19.7
 19.8 19.9 20. ]
z: [[1. 1. 1.]
 [1. 1. 1.]]


8.Using the available Numpy functions on array x from problem  7 , find the average and the standard deviation of the value in this array. Redefine x as an array with all these values sorted in numerical order.

In [9]:
# sort array and store with new name
sort_x = np.sort(x)
# print sorted array
print('sorted:', sort_x)
# calculate mean of array
mean_x = np.mean(x)
# print mean of array
print('mean:',mean_x)
# calculate standard deviation of array
std_x = np.std(x)
# print standard deviation of array
print('std:',std_x)


sorted: [ 2  9 10 12 20]
mean: 10.6
std: 5.782732917920384


9. Create a 10x10 array with random values and find the minimum and maximum values

In [10]:
# create array with random values
rand_arr = np.random.randint(1,100,(10,10))
# calculate min of array
rand_min = np.min(rand_arr)
# calculate max of array
rand_max = np.max(rand_arr)

# dipslay array, its min and max values
print(f' 10x10 : {rand_arr} \n minimum: {rand_min} \n maximum:{rand_max}')

 10x10 : [[28 12 38 88  7 28 72  1 66 16]
 [82 90 11 60 50 35 36 77 54 75]
 [22 61 56 66 80 79 90 16 13 55]
 [77 82 19 69 99 75 39 62 14 62]
 [43 62 60 43  3  7 84 18 94 32]
 [ 4  5 63 20 49 14 17 66 34 69]
 [ 5 78 37 87 91 27 14 39 36 69]
 [ 5 99 76 50 28 69 86 67 19  2]
 [42 43 56 57  7 39 19  7 80 88]
 [81  1  2 13 65  9 76  7 35 98]] 
 minimum: 1 
 maximum:99


10. Create a 3x3 matrix with values ranging from 0 to 8

In [11]:
# create matrix
arr_tre = np.arange(0,9).reshape((3,3))
# display matrix
arr_tre

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

11.  Generates an array [[1 2 3] [4 5 6]]

In [12]:
# create array
gen_arr = np.arange(1,7).reshape((2,3))
# display array
gen_arr

array([[1, 2, 3],
       [4, 5, 6]])

12. Generates an array [0 2.5 5 7.5 10]

In [13]:
# create array
gen_arr2 = np.linspace(0, 10, 5)
# display array
gen_arr2

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

13. Generates an 3x3 array of zeros

In [14]:
# create array
zeroes_arr = np.zeros((3,3))
# display array
zeroes_arr

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

14. Create array from 0.1 to 10 with 12 elements, inclusively

In [16]:
# create array
twel_arr = np.linspace(0.1, 10, 12)
# display array
twel_arr

array([ 0.1,  1. ,  1.9,  2.8,  3.7,  4.6,  5.5,  6.4,  7.3,  8.2,  9.1,
       10. ])

15. Create a matrix with seven columns and five rows of ten(10).

In [18]:
# create array
sev_arr = np.full((5,7), 10)
# convert to matrix
sev_mat = np.matrix(sev_arr)
# display matrix
sev_mat

matrix([[10, 10, 10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10, 10, 10]])

16. What is the difference between numpy and list?

**Answer :** Numpy can take multiple dimensions but lists only take a one dimensional input

17. Create a 1D array of ones consisting of  50  values. Change the values of the array so that the values alternate between ones and zeros ie  1,0,1,0,1,0,1,0,1...  ensuring that the starting value is  1 

In [19]:
# create array containing ones
ones_arr = np.ones(50, dtype = int)
# iterate through every other number from 1 to 50
for i in range(1,50,2):
    # changing array value using index
    ones_arr[i] = 0
# display array
ones_arr

array([1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 1, 0])

18. Generate a  10×10  matrix of zeros.
Make this matrix an identity matrix

In [20]:
# create array
ide_arr = np.eye(10)
# display array
ide_arr

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

19. Generate an array x to be a  10×10  array of zeros. Redefine its diagonal components (from left to right) to equal one

In [22]:
# create array
diag_arr = np.zeros((10,10))
# fill diagonal of array with 1
np.fill_diagonal(diag_arr, 1)
# display array
diag_arr

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

20. What is the dot products of this two matrix [[1,2],[3,4]] and [[5,6],[7,8]]

In [23]:
# create two arrays
one_arr = np.array([[1,2],[3,4]])
two_arr = np.array([[5,6],[7,8]])
# calculate dot product
dot = np.dot(one_arr,two_arr)
# display dot product
dot

array([[19, 22],
       [43, 50]])

21.  Multiply these two matrix [[1,2],[3,4]] and [[5,6],[7,8]]

In [25]:
# create arrays
one_arr = np.array([[1,2],[3,4]])
two_arr = np.array([[5,6],[7,8]])
# convert arrays to matrix and multiply
mult_mat = np.matrix(one_arr)*np.matrix(two_arr)
# display matrix
mult_mat

matrix([[19, 22],
        [43, 50]])

22. Multiply this matrix  [[1,2],[3,4]] by a  scalar value of 5

In [28]:
# create array
sca_arr = np.array([[1,2],[3,4]])
# multiply array by 5
scalar = 5 * np.matrix(sca_arr)
# display results of operation
scalar

matrix([[ 5, 10],
        [15, 20]])

23. A = [[1,2],[3,4]] and B = transpose of A. Calculate AxB

In [29]:
# create array
A = np.array([[1,2],[3,4]])
# transpose array into another array
B = np.transpose(A)
# multiply arrays
arr_mult = A*B
# display results
arr_mult

array([[ 1,  6],
       [ 6, 16]])

24. A= [[1,2],[3,4]] and B =  [[5,6],[7,8]]. Is A x B = B x A ? Show working

In [31]:
# create arrays
A= np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])
# multiply A by B
first_mult = A*B
# multipy B by A
second_mult = B*A
#check if the two multiplications are equal
print(np.array_equal(first_mult,second_mult))

True


25. Creates an array [[0 1 2] [3 4 5]]
- Let A = first row of the matrix
- B = second row of the matrix
- C = second column of the Matrix
- D = first row, third column of the matrix
- print A , B , C, D

In [32]:
# create array
arr = np.array([[0, 1, 2], [3, 4, 5]])
# assign A to first row of array
A = arr[0]
# assign B to second row of array
B = arr[1]
# assign C to second column of array
C = arr[:,1]
# assign D to first row, third column of array
D = arr[0,2]
# display values
print("A:",A)
print("B:",B)
print("C:",C)
print("D:",D)

A: [0 1 2]
B: [3 4 5]
C: [1 4]
D: 2
